### PR TITLE
Update spray version to released 1.3.2

### PR DESCRIPTION
**Pull request by slothspot**
Since 1.3.2 spray was released, I updated spray-websocket dependency

### CODE REVIEW

**Comment by maxsang** [comment]
We would also welcome an official build of spray-websocket that only used a stable version of spray-can etc.

**Comment by dcaoyuan** [comment]
There is a reason to stay with spray 1.3.2-20140909:
https://github.com/spray/spray/pull/836

**Comment by dcaoyuan** [comment]
BTW, we're looking forward the coming akka-http, akka-stream.

**Comment by Alain-Bearez** [comment]
While reviewing the source code for "release/1.3" branch in Spray repository, it seems to me that the referenced code (https://github.com/spray/spray/pull/836/files) has been merged from the #836 pull request.

The 1.3.2 changelog (https://github.com/spray/spray/commit/dbfdfb64d93751009722a0ed534c642dffc04871) mentions the ```Connection: Upgrade``` rendering as one of the fixes in the release (```+ add support for rendering of 'Connection: Upgrade' response header```).

**Pull request merged**
